version: "2"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    networks:
      - stegobot

  database:
    container_name: database
    image: postgres:latest
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: Q12345q
      POSTGRES_USER: stego
      POSTGRES_DB: stego
    networks:
      - stegobot

  cache:
    container_name: redis
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=Q12345q
    networks:
      - stegobot
      
networks:
  stegobot:
    driver: bridge
