version: "2"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
  
  backend:
    container_name: backend
    build: .
    ports:
      - "${BACKEND_PORT}:80"
    depends_on:
      - rabbitmq
      - cache
    environment:
      - DATABASE_CONNECTION_STRING=Server=database;Port=5432;Database=stego;User Id=stego;Password=Q12345q; Include Error Detail=true;
      - REDIS_CONNECTION_STRING=cache,password=Q12345q
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
    restart: always

  database:
    container_name: database
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: Q12345q
      POSTGRES_USER: stego
      POSTGRES_DB: stego
    networks:
      - app_net

  cache:
    container_name: redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=Q12345q
    networks:
      - app_net
