//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.Services {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bot.Services.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UnauthorizedStatusMsg {
            get {
                return ResourceManager.GetString("UnauthorizedStatusMsg", resourceCulture);
            }
        }
        
        internal static string AuthorizedAlertMsg {
            get {
                return ResourceManager.GetString("AuthorizedAlertMsg", resourceCulture);
            }
        }
        
        internal static string DeauthorizedAlertMsg {
            get {
                return ResourceManager.GetString("DeauthorizedAlertMsg", resourceCulture);
            }
        }
        
        internal static string IncorrectTokenMsg {
            get {
                return ResourceManager.GetString("IncorrectTokenMsg", resourceCulture);
            }
        }
        
        internal static string SendTokenMsg {
            get {
                return ResourceManager.GetString("SendTokenMsg", resourceCulture);
            }
        }
        
        internal static string Dialogue {
            get {
                return ResourceManager.GetString("Dialogue", resourceCulture);
            }
        }
        
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        internal static string SubscribeOnMsg {
            get {
                return ResourceManager.GetString("SubscribeOnMsg", resourceCulture);
            }
        }
        
        internal static string UnsubscibeFromMsg {
            get {
                return ResourceManager.GetString("UnsubscibeFromMsg", resourceCulture);
            }
        }
        
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
    }
}
